---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-wiring-githedgehog-com-v1alpha2-connection
  failurePolicy: Fail
  name: mconnection.kb.io
  rules:
  - apiGroups:
    - wiring.githedgehog.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - connections
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wiring-githedgehog-com-v1alpha2-connection
  failurePolicy: Fail
  name: vconnection.kb.io
  rules:
  - apiGroups:
    - wiring.githedgehog.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - connections
  sideEffects: None
