apiVersion: wiring.githedgehog.com/v1alpha2
kind: SwitchPort
metadata:
  labels:
    wiring.githedgehog.com/rack: rack-1
    wiring.githedgehog.com/switch: switch-1
  name: some-switch-1--port-1
spec:
  role: leaf-fabric
  isConnected: true
  nosPortNum: 0
  nosPortName: Ethernet0
  portSpeed: 10G
  connectorType: qsfp
  cableType: optical
  neighbor:
    # TODO: check with Amit
    #server_port: server1-ep1
    switch:
      name: switch1
      port: switch1-ethernet10
  onie:
    portNum: 0
    portName: eth0
    bootstrapIP: 192.168.1.1/24
    vlan: 300
    routes:
      - gateway: 192.168.1.254
        destinations:
          - 10.42.0.0/16
          - 10.43.0.0/16
  interfaces:
    - name: Ethernet0.100 # This is interface.vlanid for the subinterface
      vlans:
        - 100
      ipAddress: 169.254.1.1/31
      bgpEnabled: true
      bfdEnabled: true
    - name: Ethernet1.200 # This is interface.vlanid for the subinterface
      vlans:
        - 200
      ipAddress: 169.254.1.2/31
      bgpEnabled: true
      bfdEnabled: true
    - name: Ethernet1.300 # This is interface.vlanid for the subinterface
      vlans:
        - 300
      ipAddress: 169.254.1.300/31
      bgpEnabled: true
      bfdEnabled: true
  adminState: down
  vrf: default

---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: SwitchPort
metadata:
  labels:
    wiring.githedgehog.com/rack: rack-1
    wiring.githedgehog.com/switch: switch-1
  name: some-switch-1--port-2
spec:
  role: spine-fabric
  isConnected: true
  nosPortNum: 0
  nosPortName: Ethernet0
  portSpeed: 10G
  connectorType: qsfp
  cableType: optical
  neighbor:
    # TODO: check with Amit
    # server_port: server1-ep1
    switch:
      name: switch1
      port: switch1-ethernet10
  onie:
    portNum: 0
    portName: eth1
    bootstrapIP: 1.1.1.1/24
    vlan: 300
    routes:
      - gateway: 1.1.1.254
        destinations:
          - 10.42.0.0/16
          - 10.43.0.0/16
  interfaces:
    - name: Ethernet0.100 # This is interface.vlanid for the subinterface
      vlans:
        - 100
      ipAddress: 169.254.1.1/31
      bgpEnabled: true
      bfdEnabled: true
    - name: Ethernet1.200 # This is interface.vlanid for the subinterface
      vlans:
        - 200
      ipAddress: 169.254.1.2/31
      bgpEnabled: true
      bfdEnabled: true
    - name: Ethernet1.300 # This is interface.vlanid for the subinterface
      vlans:
        - 300
      ipAddress: 169.254.1.300/31
      bgpEnabled: true
      bfdEnabled: true
  adminState: down
  vrf: default

---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: SwitchPort
metadata:
  labels:
    wiring.githedgehog.com/rack: rack-1
    wiring.githedgehog.com/switch: switch-1
  name: some-switch-1--port-4
spec:
  role: leaf-server-l2-untagged
  isConnected: true
  nosPortNum: 0
  nosPortName: Ethernet0
  portSpeed: 10G
  connectorType: qsfp
  cableType: optical
  neighbor:
    # TODO: check with Amit
    # server_port: server1-ep1
    switch:
      name: switch1
      port: switch1-ethernet0
  onie:
    portNum: 0
    portName: eth1
    bootstrapIP: 1.1.1.1/24
    vlan: 300
    routes:
      - gateway: 1.1.1.254
        destinations:
          - 10.42.0.0/16
          - 10.43.0.0/16
  interfaces:
    - name: Ethernet0 # This is interface.vlanid for the subinterface
      vlans:
        - 100
      ipAddress: "" #No ip required this is vlan member switchport
      bgpEnabled: false
      bfdEnabled: true
  adminState: down
  vrf: default # does not matter
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: SwitchPort
metadata:
  labels:
    wiring.githedgehog.com/rack: rack-1
    wiring.githedgehog.com/switch: switch-1
  name: some-switch-1--port-3
spec:
  role: leaf-server-l2-untagged
  isConnected: true
  nosPortNum: 0
  nosPortName: Ethernet0
  portSpeed: 10G
  connectorType: qsfp
  cableType: optical
  neighbor:
    # TODO: check with Amit
    # server_port: server1-ep1
    switch:
      name: switch1
      port: switch1-ethernet0
  onie:
    portNum: 0
    portName: eth1
    bootstrapIP: 1.1.1.1/24
    vlan: 300
    routes:
      - gateway: 1.1.1.254
        destinations:
          - 10.42.0.0/16
          - 10.43.0.0/16
  interfaces:
    - name: Ethernet0 # This is interface.vlanid for the subinterface
      vlans:
        - 1
      ipAddress: 192.168.1.2 #No ip required this is vlan member switchport
      bgpEnabled: true
      bfdEnabled: true
  adminState: down
  vrf: default
