apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    wiring.githedgehog.com/rack: rack1
  name: server-1
spec:
  serverConnections:
    - isBundled: false
      connectionType: control-connection
      nics:
        - nicName: eth0
          nicIndex: 1
          neighbor:
            switch:
              name: leaf1
              port: Ethernet0
      ctrlMgmtInfo:
        ipAddress: 192.168.1.1/24
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    wiring.githedgehog.com/rack: rack1
  name: server-management-unbundled
spec:
  serverConnections:
    - isBundled: false
      connectionType: management-connection
      nics:
        - nicName: eth0
          nicIndex: 1
          neighbor:
            switch:
              name: leaf1
              port: Ethernet0
      ctrlMgmtInfo:
        ipAddress: 192.168.1.1/24
        vlanInfo:
          vlanID: 200

---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    wiring.githedgehog.com/rack: rack1
  name: server-management-bundled-sample
spec:
  serverConnections:
    - isBundled: false
      bundleConfig:
        bundleType: LAG
      connectionType: management-connection
      nics:
        - nicName: eth0
          nicIndex: 1
          neighbor:
            switch:
              name: leaf1
              port: Ethernet0
        - nicName: eth1
          nicIndex: 2
          neighbor:
            switch:
              name: leaf1
              port: Ethernet2
      ctrlMgmtInfo:
        ipAddress: 192.168.1.1/24
        vlanInfo:
          vlanID: 200
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    wiring.githedgehog.com/rack: rack1
  name: server-control-routed-sample
spec:
  serverConnections:
    - isBundled: false
      connectionType: control-connection
      nics:
        - nicName: eth0
          nicIndex: 1
          neighbor:
            switch:
              name: leaf1
              port: Ethernet5
      ctrlMgmtInfo:
        ipAddress: 192.168.1.2/30
---

