# permissions for end users to view controlagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: controlagent-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fabric
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
  name: controlagent-viewer-role
rules:
- apiGroups:
  - agent.githedgehog.com
  resources:
  - controlagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.githedgehog.com
  resources:
  - controlagents/status
  verbs:
  - get
