---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agent.githedgehog.com
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.githedgehog.com
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - agent.githedgehog.com
  resources:
  - agents/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wiring.githedgehog.com
  resources:
  - connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wiring.githedgehog.com
  resources:
  - connections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - wiring.githedgehog.com
  resources:
  - switches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wiring.githedgehog.com
  resources:
  - switches/status
  verbs:
  - get
  - patch
  - update
