# permissions for end users to view ipv4namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipv4namespace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fabric
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
  name: ipv4namespace-viewer-role
rules:
- apiGroups:
  - vpc.githedgehog.com
  resources:
  - ipv4namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpc.githedgehog.com
  resources:
  - ipv4namespaces/status
  verbs:
  - get
