# permissions for end users to edit vlannamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vlannamespace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fabric
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
  name: vlannamespace-editor-role
rules:
- apiGroups:
  - wiring.githedgehog.com
  resources:
  - vlannamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wiring.githedgehog.com
  resources:
  - vlannamespaces/status
  verbs:
  - get
