###
### rack-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Rack
metadata:
  name: rack-1
spec:
---
###
### switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: b7e0848d-15f9-5f46-ac21-1710a7b792f0
    fabric.githedgehog.com/rack: rack-1
  name: switch-1
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "1"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: 81c9671f-0b80-5a45-b946-686de0b9aaa9
    fabric.githedgehog.com/rack: rack-1
  name: switch-2
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "2"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### control-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: 1e9df880-96d7-5806-8413-0d1d4fd19df2
    fabric.githedgehog.com/rack: rack-1
  name: control-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "3"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
  type: control
---
###
### server-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: cf8e1bf2-ebc3-552a-a149-4112ce95fc2c
    fabric.githedgehog.com/rack: rack-1
  name: server-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "4"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### server-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: 1fee30cf-7a35-5ad8-9e5d-2b6ec0e56d0c
    fabric.githedgehog.com/rack: rack-1
  name: server-2
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "5"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### control-1--mgmt--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
  name: control-1--mgmt--switch-1
spec:
  management:
    link:
      server:
        ip: 192.168.101.1/31
        port: control-1/eth1
      switch:
        ip: 192.168.101.0/31
        oniePortName: eth0
        port: switch-1/Management0
---
###
### control-1--mgmt--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: control-1--mgmt--switch-2
spec:
  management:
    link:
      server:
        ip: 192.168.102.1/31
        port: control-1/eth2
      switch:
        ip: 192.168.102.0/31
        oniePortName: eth0
        port: switch-2/Management0
---
###
### server-1--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/server-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-1--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-1/eth1
      switch:
        port: switch-1/Ethernet4
    - server:
        port: server-1/eth2
      switch:
        port: switch-2/Ethernet4
---
###
### server-2--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/server-2: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-2--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-2/eth1
      switch:
        port: switch-1/Ethernet5
    - server:
        port: server-2/eth2
      switch:
        port: switch-2/Ethernet5
---
###
### switch-1--mclag-domain--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.fabric.githedgehog.com/rack-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: switch-1--mclag-domain--switch-2
spec:
  mclagDomain:
    peerLinks:
    - switch1:
        port: switch-1/Ethernet0
      switch2:
        port: switch-2/Ethernet0
    - switch1:
        port: switch-1/Ethernet1
      switch2:
        port: switch-2/Ethernet1
    sessionLinks:
    - switch1:
        port: switch-1/Ethernet2
      switch2:
        port: switch-2/Ethernet2
    - switch1:
        port: switch-1/Ethernet3
      switch2:
        port: switch-2/Ethernet3
