###
### rack-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Rack
metadata:
  name: rack-1
spec:
---
###
### default
###
apiVersion: vpc.githedgehog.com/v1alpha2
kind: NAT
metadata:
  name: default
spec:
  dnat:
    pool:
    - 192.168.91.192/26
  subnet: 192.168.91.0/24
---
###
### switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: b7e0848d-15f9-5f46-ac21-1710a7b792f0
  name: switch-1
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "1"
  locationSig:
    sig: <undefined>
    uuidSig: <undefined>
---
###
### switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: 81c9671f-0b80-5a45-b946-686de0b9aaa9
  name: switch-2
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "2"
  locationSig:
    sig: <undefined>
    uuidSig: <undefined>
---
###
### control-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: control
  name: control-1
spec:
  type: control
---
###
### server-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-1
spec: {}
---
###
### server-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-2
spec: {}
---
###
### server-3
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-3
spec: {}
---
###
### server-4
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-4
spec: {}
---
###
### control-1--mgmt--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: management
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
  name: control-1--mgmt--switch-1
spec:
  management:
    link:
      server:
        ip: 192.168.101.1/31
        port: control-1/enp0s3
      switch:
        ip: 192.168.101.0/31
        oniePortName: eth0
        port: switch-1/Management0
---
###
### control-1--mgmt--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: management
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: control-1--mgmt--switch-2
spec:
  management:
    link:
      server:
        ip: 192.168.102.1/31
        port: control-1/enp0s4
      switch:
        ip: 192.168.102.0/31
        oniePortName: eth0
        port: switch-2/Management0
---
###
### server-1--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    server.fabric.githedgehog.com/server-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-1--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-1/enp0s2
      switch:
        port: switch-1/Ethernet5
    - server:
        port: server-1/enp0s3
      switch:
        port: switch-2/Ethernet5
---
###
### server-2--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    server.fabric.githedgehog.com/server-2: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-2--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-2/enp0s2
      switch:
        port: switch-1/Ethernet6
    - server:
        port: server-2/enp0s3
      switch:
        port: switch-2/Ethernet6
---
###
### server-3--unbundled--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: unbundled
    server.fabric.githedgehog.com/server-3: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
  name: server-3--unbundled--switch-1
spec:
  unbundled:
    link:
      server:
        port: server-3/nic0/port0
      switch:
        port: switch-1/Ethernet7
---
###
### server-4--unbundled--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: unbundled
    server.fabric.githedgehog.com/server-4: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-4--unbundled--switch-2
spec:
  unbundled:
    link:
      server:
        port: server-4/nic0/port0
      switch:
        port: switch-2/Ethernet7
---
###
### switch-1--mclag-domain--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag-domain
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: switch-1--mclag-domain--switch-2
spec:
  mclagDomain:
    peerLinks:
    - switch1:
        port: switch-1/Ethernet1
      switch2:
        port: switch-2/Ethernet1
    - switch1:
        port: switch-1/Ethernet2
      switch2:
        port: switch-2/Ethernet2
    sessionLinks:
    - switch1:
        port: switch-1/Ethernet3
      switch2:
        port: switch-2/Ethernet3
    - switch1:
        port: switch-1/Ethernet4
      switch2:
        port: switch-2/Ethernet4
---
###
### switch-1--nat--default
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  name: switch-1--nat--default
spec:
  nat:
    link:
      nat:
        port: default
      switch:
        anchorIP: 192.168.91.129/27
        ip: 192.168.91.0/31
        neighborIP: 192.168.91.1/31
        port: switch-1/Ethernet0
        remoteAS: 65102
        snat:
          pool:
          - 192.168.91.128/27
---
###
### switch-2--nat--default
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  name: switch-2--nat--default
spec:
  nat:
    link:
      nat:
        port: default
      switch:
        anchorIP: 192.168.91.97/27
        ip: 192.168.91.65/31
        neighborIP: 192.168.91.64/31
        port: switch-2/Ethernet0
        remoteAS: 65102
        snat:
          pool:
          - 192.168.91.96/27
