###
### rack-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Rack
metadata:
  name: rack-1
spec:
---
###
### default
###
apiVersion: vpc.githedgehog.com/v1alpha2
kind: NAT
metadata:
  name: default
spec:
  dnatPool:
  - 172.2.2.192/27
  subnet: 172.2.2.1/24
status:
  dnat:
    assigned: 0
    assignedList: null
    available: 0
---
###
### switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: b7e0848d-15f9-5f46-ac21-1710a7b792f0
  name: switch-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "1"
  locationSig:
    sig: <undefined>
    uuidSig: <undefined>
  portGroupSpeeds:
    "1": 10G
    "12": 10G
  role: server-leaf
status:
---
###
### switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: 81c9671f-0b80-5a45-b946-686de0b9aaa9
  name: switch-2
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "2"
  locationSig:
    sig: <undefined>
    uuidSig: <undefined>
  portGroupSpeeds:
    "1": 10G
    "12": 10G
  role: server-leaf
status:
---
###
### control-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: control
  name: control-1
spec:
  type: control
---
###
### server-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-1
spec: {}
---
###
### server-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-2
spec: {}
---
###
### server-3
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/server-type: ""
  name: server-3
spec: {}
---
###
### control-1--mgmt--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: management
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
  name: control-1--mgmt--switch-1
spec:
  management:
    link:
      server:
        ip: 192.168.101.1/31
        port: control-1/enp7s0
      switch:
        ip: 192.168.101.0/31
        oniePortName: eth0
        port: switch-1/Management0
status:
---
###
### control-1--mgmt--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: management
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: control-1--mgmt--switch-2
spec:
  management:
    link:
      server:
        ip: 192.168.102.1/31
        port: control-1/enp8s0
      switch:
        ip: 192.168.102.0/31
        oniePortName: eth0
        port: switch-2/Management0
status:
---
###
### server-1--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    server.fabric.githedgehog.com/server-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-1--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-1/enp7s0
      switch:
        port: switch-1/Ethernet8
    - server:
        port: server-1/enp8s0
      switch:
        port: switch-2/Ethernet8
status:
---
###
### server-2--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    server.fabric.githedgehog.com/server-2: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-2--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-2/enp7s0
      switch:
        port: switch-1/Ethernet9
    - server:
        port: server-2/enp8s0
      switch:
        port: switch-2/Ethernet9
status:
---
###
### server-3--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    server.fabric.githedgehog.com/server-3: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-3--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-3/ens3f0
      switch:
        port: switch-1/Ethernet4
    - server:
        port: server-3/ens3f1
      switch:
        port: switch-2/Ethernet4
status:
---
###
### switch-1--mclag-domain--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag-domain
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: switch-1--mclag-domain--switch-2
spec:
  mclagDomain:
    peerLinks:
    - switch1:
        port: switch-1/Ethernet48
      switch2:
        port: switch-2/Ethernet48
    - switch1:
        port: switch-1/Ethernet56
      switch2:
        port: switch-2/Ethernet56
    sessionLinks:
    - switch1:
        port: switch-1/Ethernet64
      switch2:
        port: switch-2/Ethernet64
    - switch1:
        port: switch-1/Ethernet68
      switch2:
        port: switch-2/Ethernet68
status:
---
###
### switch-1--nat--default
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: nat
    switch.fabric.githedgehog.com/switch-1: "true"
  name: switch-1--nat--default
spec:
  nat:
    link:
      nat:
        port: default
      switch:
        ip: 192.168.91.0/31
        neighborIP: 192.168.91.1
        port: switch-1/Ethernet0
        remoteAS: 65102
        snat:
          pool:
          - 172.2.2.0/27
status:
---
###
### switch-2--nat--default
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: nat
    switch.fabric.githedgehog.com/switch-2: "true"
  name: switch-2--nat--default
spec:
  nat:
    link:
      nat:
        port: default
      switch:
        ip: 192.168.91.65/31
        neighborIP: 192.168.91.64
        port: switch-2/Ethernet0
        remoteAS: 65102
        snat:
          pool:
          - 172.2.2.96/27
status:
