apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    app.kubernetes.io/name: connection
    app.kubernetes.io/instance: connection-sample
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fabric
  name: connection-sample
spec:
  # TODO(user): Add fields here
