apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fabric
  name: server-sample
spec:
  # TODO(user): Add fields here
