apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    app.kubernetes.io/name: switch
    app.kubernetes.io/instance: switch-sample
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fabric
  name: switch-sample
spec:
  # TODO(user): Add fields here
