apiVersion: wiring.githedgehog.com/v1alpha2
kind: SwitchGroup
metadata:
  labels:
    app.kubernetes.io/name: switchgroup
    app.kubernetes.io/instance: switchgroup-sample
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fabric
  name: switchgroup-sample
spec:
  # TODO(user): Add fields here
